#!/usr/bin/env ruby
base_path = File.dirname(__FILE__)
$LOAD_PATH.unshift(base_path) unless $LOAD_PATH.include?(base_path)

require 'commands/init'
GitFlow.should_run = false

at_exit { GitFlow.run(*(['init'] + ARGV)) }
